image: python

stages:
- test
- build

before_script:
- curl -O https://bootstrap.pypa.io/get-pip.py
- python get-pip.py
- pip install -r requirements-dev.txt

#after_script:
#- pip install codecov
#- codecov --token=$token

python2:
  image: python:2.7
  stage: test
  script: tox -e py27

python36:
  image: python:3.6
  stage: test
  script: tox -e py36

linters:
  image: python:3.6
  stage: test
  script: tox -e linters

build:
  stage: build
  script: tox -e build
  artifacts:
    paths:
    - dist/
    expire_in: 1 month
