# Tox (http://tox.testrun.org/)

[tox]
envlist = py311, py312, py313, py314, linters

[testenv]
deps = pytest
commands =
    {envpython} --version
    {envpython} -m ensurepip --default-pip
    {envpython} -m pip install .
    pytest clitools

[testenv:linters]
skip_install = true
allowlist_externals = rm
deps = -rrequirements-dev.txt
commands = flake8 {posargs} --count --statistics
    flake8 --version
    check-manifest -v

# Release tooling
[testenv:build]
skip_install = true
allowlist_externals = rm
deps =
    build
commands =
    rm -rf build dist
    python -m build --sdist --wheel

[gh-actions]
python =
    3.11: py311
    3.12: py312
    3.13: py313, linters
    3.14: py314
